name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push, pull_request]

env:
  IMAGE_NAME: my-app-image

jobs:
  build_app:
    runs-on: ubuntu-latest
    container: node:18
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run test
        run: npm run test

      - name: Run build
        run: npm run build

      - name: check code format quality
        run: npm run lint && npx prettier --check

  build_docker_container:
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version

      - name: Run docker-compose up
        run: docker-compose up -d

  push_to_dockerhub:
    runs-on: ubuntu-latest
    needs: build_docker_container
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      #using it to be able to build multi-platform images, export cache, etc.
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: cuong0402/cuong-docker-repository-demo:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max

  deploy-staging:
    name: 🚧 Deploy to staging
    runs-on: ubuntu-latest
    needs: push_to_dockerhub
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy backend to staging server
        run: ssh user@staging-host "docker pull ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest && docker run -d --rm --name staging-backend ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest"

  deploy-production:
    name: 🚀 Deploy to production
    runs-on: ubuntu-latest
    needs: push_to_dockerhub
    steps:
      - name: Wait for manual approval
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: manual-approval
      - name: Deploy backend to production
        run: ssh user@prod-host "docker pull ... && docker run -d --name prod-backend ..."
